### PR TITLE
pix2pix blog

### PR DESCRIPTION
**Pull request by aniketmaurya**

### CODE REVIEW

**Comment by aniketmaurya** [comment]
<p>Sure, I will add extra resources and links wherever applicable</p>

---

 <a href='https://app.reviewnb.com/LibreCV/blog/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aniketmaurya** [comment]
<p>Oh yes! I was about to do that but forgot among other things.</p>

---

 <a href='https://app.reviewnb.com/LibreCV/blog/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aniketmaurya** [comment]
<p>If I understand the second point correctly - </p><p>The generator in Pix2Pix learns from pair of target (real) and conditional images to translate the conditional image into target image. The target image generated by Generator is fake, right?</p><p>Also in the loss function we don't have such criteria that optimizes the network that if a target image is fed to the generator then produce the exact same image (generate image = input image)</p>

---

 <a href='https://app.reviewnb.com/LibreCV/blog/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by edgarriba — APPROVED** [review]

**Comment by edgarriba** [comment]
@Borda Could you review ?

**Pull request merged**
