### PR TITLE
blog post for continuum

### PR DESCRIPTION
**Pull request by TLESORT**

### CODE REVIEW

**Review by prlz77 — COMMENTED** [review]
I don't know how to review a notebook inline so I will write it here:

# Introduction
prevent researchers -> "free" or "liberate" researchers
also proposes to log algorightm.. -> also includes tools for logging ...
designed to pluggable -> designed to be pluggable

# Create your first scenario
Instance Incremental learning -> add a title and show a picture.

For the rest, LGTM

**Comment by edgarriba** [comment]
@TLESORT apparently there's also a building issue :(

@aniketmaurya Have you ever faced this ?

**Comment by edgarriba** [comment]
@TLESORT just to make sure - are you able to build in local ?

**Comment by TLESORT** [comment]
I will look at this asap

**Comment by TLESORT** [comment]
<p>There is no problem on colab I will test locally</p>

**Comment by TLESORT** [comment]
The notebook also works locally, I don't know what is the problem.... It seems it comes from jekyll

**Comment by edgarriba** [comment]
@TLESORT there was an issue with the title :laughing: 

image

**Comment by edgarriba** [comment]
lets coordinate to promote on Tuesday (best engaging day) in twitter and linkedin

**Pull request merged**
